[atom]
id = "pkdjz"
version = "0.1.0"
system = true
propagate = true

[std]
features = ["lib"]

[fetch.nixpkgs-atom]
name = "nixpkgs-atom"

[fetch.zed]
name = "zed"
type = "flake"

[fetch.omnix]
name = "omnix"
type = "flake"

[backend.nix]
fetcher = "flake-lock"